### ISSUE TITLE
PA Review: Group DM's

### ISSUE THREAD

**Issue by ameet01** [ameet01/slack#10]

**Comment by evhumphrey** [comment]
- [x] Prevent duplicates (slack will continue off an old conversation if it exists)

**Comment by ameet01** [comment]
I think I completed it. If I select the same exact users as a current group dm, then it will redirect to that and not create a new one

**Comment by evhumphrey** [comment]
Nice!

There are a couple issues: 

- [x] BUG: if you create a message with user1 and user2, then try to create it again, it will successfully take you to the existing conversation. However, your app status will say "#user1, user2 and 40 others" after doing so, which doesn't seem right.
- [x] Clicking on the create DM button takes a while to open. My guess is you're waiting for the response before showing the modal. Instead, you should open the modal without waiting for the response, but have some sort of loading status in the meantime

**Comment by ameet01** [comment]
Fixed I believe, let me know!

**Comment by evhumphrey** [comment]
Nice job 💯
