### ISSUE TITLE
PA Review: Channels

### ISSUE THREAD

**Issue by ameet01** [ameet01/slack#4]

**Comment by evhumphrey** [comment]
- [x] There should be a UI button to create a channel before this MVP is complete 

(_Edited:_ whoops, noticed you haven't assigned me as reviewer yet 👻 )

**Comment by evhumphrey** [comment]
Per our conversation:

- [x] Have a way to browse channels (fetch all channels and display them) and create a Subscription

**Comment by evhumphrey** [comment]
- [x] Prevent duplicate channel names
